Repository nextcloud/circles, pull requests merged in 2021-08, with the labels that each got.

#758 include and config path in loopback
  lib/Command/CirclesCheck.php
  lib/Controller/RemoteController.php
  lib/Handlers/WebfingerHandler.php
  lib/Service/ConfigService.php
  lib/Service/InterfaceService.php
Labels: backport-request

#760 cleaning old code
  lib/FederatedItems/SingleMemberAdd.php
Labels: backport-request

#764 do not remove non-yet-members during migration
  lib/Migration/RemoveDeadShares.php
Labels: backport-request

#768 members cannot directly join a Secret Circle
  lib/Model/Member.php
Labels: backport-request

#775 Check if `$knownPath` is set before invoking `rtrim()`
  lib/Service/ConfigService.php
Labels: 3. to review, backport-request

#778 generate quick members' memberships during migration
  lib/Service/MembershipService.php
  lib/Service/MigrationService.php
Labels: 3. to review, backport-request, bug

#781 verify shareType in params
  lib/Collaboration/v2/CollaboratorSearchPlugin.php
Labels: backport-request

#780 details on non-visible (but open) circles
  lib/Command/CirclesDetails.php
  lib/Controller/AdminController.php
  lib/Controller/LocalController.php
  lib/Db/CoreQueryBuilder.php
  lib/Model/Probes/CircleProbe.php
  lib/Service/CircleService.php
Labels: backport-request

#784 fix definition on single circles
  lib/Service/CircleService.php
Labels: backport-request

#790 emulate initiator on CircleJoin
  lib/Db/MemberRequest.php
  lib/FederatedItems/CircleLeave.php
  lib/Service/CircleService.php
Labels: backport-request

#792 owner of NO_OWNER should not have memberships cached
  lib/Db/CircleRequest.php
  lib/Db/CoreQueryBuilder.php
  lib/Model/Probes/MemberProbe.php
  lib/Service/MemberService.php
  lib/Service/MembershipService.php
Labels: 3. to review, backport-request

#793 fix notification when invited to a circle
  lib/Notification/Notifier.php
  lib/Service/MemberService.php
Labels: 2. developing, backport-request

#803 exception on non visible circle
  lib/FederatedItems/CircleLeave.php
Labels: 3. to review, backport-request, bug

#804 force join_request on old secret circles
  lib/Service/MigrationService.php
Labels: 4. to release, backport-request, bug
