Repository nextcloud/circles, pull requests merged in 2021-03, with the labels that each got.

#566 Allow to get circle details with forceAll
  lib/Service/CirclesService.php
Labels: 3. to review, backport-request, bug

#571 fix setup with nc21
  lib/Migration/Version0019Date20200603080001.php
Labels: 3. to review

#480 l10n: Add a dot in the text string
  templates/navigate.php
Labels: design
