Repository nextcloud/circles, pull requests merged in 2022-06, with the labels that each got.

#1050 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1051 confirmKey must be uuid
  lib/Service/RemoteStreamService.php
  lib/Tools/Traits/TStringTools.php
Labels: 3. to review, backport-request, bug, high, security

#1040 using deserializeList instead
  lib/Service/ShareWrapperService.php
  lib/Tools/Traits/TDeserialize.php
Labels: 3. to review, backport-request, enhancement

#1012 [occ] display information about freshly created circle
  lib/Command/CirclesCreate.php
Labels: 3. to review, backport-request

#1037 recursive setOptions()
  lib/Db/CoreQueryBuilder.php
Labels: backport-request

#1074 Fix return type of ExtendedQueryBuilder->exprFilterBitwise()
  lib/Tools/Db/ExtendedQueryBuilder.php
Labels: 3. to review, bug

#1063 log failed member generation
  lib/FederatedItems/MassiveMemberAdd.php
Labels: backport-request

#1023 confirm migration feasibility
  lib/Service/MigrationService.php
Labels: backport-request

#1084 Revert "[stable23] log failed member generation"
  lib/FederatedItems/MassiveMemberAdd.php
Labels: 3. to review

#1082 Revert "[stable22] log failed member generation"
  lib/FederatedItems/MassiveMemberAdd.php
Labels: 3. to review

#1085 Revert "[stable23] confirm migration feasibility"
  lib/Service/MigrationService.php
Labels: 3. to review

#1083 Revert "confirm migration feasibility"
  lib/Service/MigrationService.php
Labels: 3. to review

#1087 Revert "[stable22] confirm migration feasibility"
  lib/Service/MigrationService.php
Labels: 3. to review

#1091 Fix getAllShare crash
  lib/ShareByCircleProvider.php
Labels: 3. to review
