Repository nextcloud/circles, pull requests merged in 2022-10, with the labels that each got.

#1169 refresh cache on demand
  lib/CirclesManager.php
Labels: backport-request

#1168 emulate user on cron
  lib/Notification/Notifier.php
  lib/Service/FederatedUserService.php
Labels: 3. to review, backport-request

#1183 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#1180 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1182 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#1184 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies
