Repository nextcloud/circles, pull requests merged in 2022-07, with the labels that each got.

#1106 [stable24] Avoid using non-existing \OCP\Server::get
  lib/Model/ShareWrapper.php
Labels: 3. to review, backport-request, bug, high, regression

#1110 Update PHPUnit workflow
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
Labels: 3. to review, backport-request

#1103 Fix the translations
  lib/Model/ShareWrapper.php
Labels: 3. to review, backport-request

#1115 Rename selectors for files app elements
  js/files/circles.files.list.js
  templates/files/list.php
Labels: 3. to review

#1116 Further cleanup of markup
  templates/files/list.php
Labels: 3. to review

#1112 enforce event on circle creation
  lib/Service/FederatedEventService.php
Labels: backport-request

#1117 Add `$shallow` arg to `ShareByCircleProvider::getSharesInFolder`
  lib/Db/ShareWrapperRequest.php
  lib/Service/ShareWrapperService.php
  lib/ShareByCircleProvider.php
  lib/ShareByCircleProviderDeprecated.php
Labels: 3. to review, enhancement
