Repository nextcloud/circles, pull requests merged in 2022-09, with the labels that each got.

#1143 [stable22] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#1144 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#1145 [stable23] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#1146 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#1155 cache getCircles when executed from an other app
  lib/CirclesManager.php
  lib/Service/CircleService.php
Labels: backport-request

#1156 [stable22] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#1158 Rename user to account/people
  README.md
  appinfo/info.xml
  lib/AppInfo/Capabilities.php
  lib/Command/CirclesSync.php
  lib/Db/DeprecatedMembersRequest.php
  lib/Model/Circle.php
  lib/Model/DeprecatedMember.php
  lib/Service/MembersService.php
  lib/Service/SyncService.php
Labels: 3. to review
