Repository nextcloud/circles, pull requests merged in 2022-08, with the labels that each got.

#1118 ignore no initiator
  lib/Listeners/DeprecatedListener.php
Labels: backport-request

#1127 ignore remnants
  lib/ShareByCircleProvider.php
Labels: backport-request

#1134 Fix IQueryFunction to string compliance
  .gitignore
  composer.lock
  lib/Db/DeprecatedCirclesRequestBuilder.php
  lib/Tools/Db/ExtendedQueryBuilder.php
  tests/psalm-baseline.xml
Labels: 4. to release, bug

#1135 Add dependabot config
  .github/dependabot.yml
Labels: 3. to review

#1141 [stable22] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1140 [stable23] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1139 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
