Repository nextcloud/circles, pull requests merged in 2022-02, with the labels that each got.

#910 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: backport-request, dependencies

#929 Fix cached circle returning bool before being parsed as JSON
  lib/Service/FederatedUserService.php
Labels: 3. to review, backport-request, bug

#913 membershipsService -> membershipService
  lib/Command/CirclesMemberships.php
Labels: 3. to review, backport-request, low

#931 block/force circle types
  lib/FederatedItems/CircleConfig.php
  lib/Service/CircleService.php
  lib/Service/ConfigService.php
Labels: 3. to review, backport-request, enhancement

#936 set member as INVITED only if not external
  lib/FederatedItems/SingleMemberAdd.php
Labels: 3. to review, backport-request, bug
