Repository nextcloud/circles, pull requests merged in 2022-01, with the labels that each got.

#890 exception on null token
  lib/ShareByCircleProvider.php
Labels: 3. to review, backport-request, bug

#892 ignore exception to group sync
  lib/Service/SyncService.php
Labels: 3. to review, backport-request, bug

#897 l10n: Improved grammar
  lib/Service/SendMailService.php
Labels: backport-request

#906 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#912 Fix loosing memberships in low depth
  lib/FederatedItems/MemberLevel.php
  lib/Model/Membership.php
  lib/Service/MaintenanceService.php
  lib/Service/MembershipService.php
Labels: 3. to review, backport-request, bug, high

#911 remove shares during circles destruction, clean orphan shares on cron
  lib/AppInfo/Application.php
  lib/Command/CirclesMaintenance.php
  lib/Listeners/Files/DestroyingCircle.php
  lib/Service/MaintenanceService.php
  lib/Service/ShareWrapperService.php
Labels: 3. to review, backport-request, bug

#903 Paginate list of Circles through OCS query parameters
  lib/Controller/AdminController.php
  lib/Controller/LocalController.php
  tests/unit/lib/Controller/AdminControllerTest.php
  tests/unit/lib/Controller/LocalControllerTest.php
Labels: 3. to review, backport-request

#917 +getSingleId(): string;
  lib/IFederatedUser.php
Labels: 3. to review, backport-request, low

#920 [stable22] Paginate Circles through OCS query parameters
  lib/Controller/AdminController.php
  lib/Controller/LocalController.php
  tests/unit/lib/Controller/AdminControllerTest.php
  tests/unit/lib/Controller/LocalControllerTest.php
Labels: 3. to review

#919 [stable23] Paginate Circles through OCS query parameters
  lib/Controller/AdminController.php
  lib/Controller/LocalController.php
  tests/unit/lib/Controller/AdminControllerTest.php
  tests/unit/lib/Controller/LocalControllerTest.php
Labels: 3. to review

#918 [stable23] remove shares during circles destruction, clean orphan shares on cron
  lib/AppInfo/Application.php
  lib/Command/CirclesMaintenance.php
  lib/Listeners/Files/DestroyingCircle.php
  lib/Service/MaintenanceService.php
  lib/Service/ShareWrapperService.php
Labels: 3. to review
