Repository nextcloud/circles, pull requests merged in 2023-07, with the labels that each got.

#1306 [stable25] refresh display name
  lib/Command/CirclesMaintenance.php
  lib/Service/MaintenanceService.php
Labels: 3. to review

#1340 chore: Remove duplicated OCP dependency
  .github/workflows/update-christophwurst-nextcloud.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1347 generate path if app _DOES_ exist
  lib/Model/ModelManager.php
Labels: backport-request

#1346 [stable25] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies
