Repository nextcloud/circles, pull requests merged in 2023-05, with the labels that each got.

#1307 Make changes to circle config synchroneous
  lib/FederatedItems/CircleConfig.php
Labels: backport-request

#1241 Create API documentation from source code using phpDocumentor
  .github/workflows/documentation.yml
  .gitignore
  README.md
  lib/Model/Circle.php
  lib/Model/Member.php
  phpDocumentor.sh
Labels: 3. to review, enhancement

#1314 Update Github workflow for psalm checks
  .github/workflows/psalm.yml
  .github/workflows/static-analysis.yml
Labels: 3. to review, tests
