Repository nextcloud/circles, pull requests merged in 2023-11, with the labels that each got.

#1298 fix incorrect Date format detection
  lib/Model/Circle.php
Labels: 3. to review, backport-request

#1421 lighter name update
  lib/Command/CirclesSync.php
  lib/Db/AccountsRequest.php
  lib/Search/LocalUsers.php
  lib/Service/FederatedUserService.php
  lib/Service/MaintenanceService.php
  lib/Service/SyncService.php
Labels: backport-request

#1435 [stable27] lighter name update
  lib/Command/CirclesSync.php
  lib/Db/AccountsRequest.php
  lib/Search/LocalUsers.php
  lib/Service/FederatedUserService.php
  lib/Service/MaintenanceService.php
  lib/Service/SyncService.php
Labels: 3. to review

#1436 [stable26] lighter name update
  lib/Command/CirclesSync.php
  lib/Db/AccountsRequest.php
  lib/Search/LocalUsers.php
  lib/Service/FederatedUserService.php
  lib/Service/MaintenanceService.php
  lib/Service/SyncService.php
Labels: 3. to review

#1398 fixes Circles icon rendering in darkmode
  img/circles.svg
Labels: feedback-requested
