Repository nextcloud/circles, pull requests merged in 2024-04, with the labels that each got.

#1545 remove debug logs
  lib/FederatedItems/SingleMemberAdd.php
Labels: backport-request

#1560 fix: Invert activity filter icon color
  img/circles-dark.svg
  lib/Activity/Filter.php
Labels: 3. to review, backport-request, bug

#1558 [stable26] set remote as email
  lib/Activity/ProviderParser.php
Labels: 2. developing

#1547 [stable26] remove debug logs
  lib/FederatedItems/SingleMemberAdd.php
Labels: 2. developing

#1536 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1541 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
