Repository nextcloud/circles, pull requests merged in 2024-08, with the labels that each got.

#1657 Migrate reuse to toml format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#1469 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1674 refactor: Migrate away from deprecated `ILogger` to PSR-3
  lib/Circles/FileSharingBroadcaster.php
  lib/Service/MiscService.php
  lib/ShareByCircleProvider.php
Labels: 3. to review, technical debt

#1628 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1673 [stable30] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1635 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1481 remove useless javascript
  css/files/circles.filelist.css
  js/files/circles.files.app.js
  js/files/circles.files.list.js
  js/jquery.js
  lib/AppInfo/Application.php
  lib/Listeners/Files/ListenerFilesLoadScripts.php
Labels: 3. to review, technical debt
