Repository nextcloud/circles, pull requests merged in 2024-11, with the labels that each got.

#1759 fix(notification): Make sure the action URL is an absolute URL
  lib/Service/NotificationService.php
Labels: 3. to review, backport-request, bug

#1758 fix(CoreQueryBuilder): Use correct member entry for circle as initiator
  lib/CirclesManager.php
  lib/Db/CoreQueryBuilder.php
  lib/Model/Federated/FederatedEvent.php
  lib/Service/CircleService.php
  lib/Service/FederatedEventService.php
  lib/Service/MemberService.php
  tests/phpunit.xml
  tests/unit/CirclesManagerTest.php
  tests/unit/lib/Controller/AdminControllerTest.php
  tests/unit/lib/Controller/LocalControllerTest.php
Labels: 3. to review, backport-request, bug

#1771 fix(FederatedUserService): Increase cache TTL for singleId to one week
  lib/Service/FederatedUserService.php
Labels: 3. to review, backport-request, bug

#1775 new daily maintenance to delete old federated events
  lib/Db/EventWrapperRequest.php
  lib/Service/MaintenanceService.php
Labels: backport-request

#1779 fix(activity): ensure absolute URL are used
  lib/Activity/ProviderParser.php
Labels: 3. to review, bug

#1727 bypass user condition on cli
  lib/Api/v1/Circles.php
Labels: backport-request

#1744 fix duplicate name on fedcircle
  lib/Db/CoreQueryBuilder.php
  lib/Db/MountPointRequest.php
  lib/Db/MountPointRequestBuilder.php
  lib/Db/MountRequest.php
  lib/Exceptions/MountPointNotFoundException.php
  lib/Migration/Version0031Date20241105133904.php
  lib/Model/ModelManager.php
  lib/Model/Mount.php
  lib/Model/Mountpoint.php
  lib/MountManager/CircleMountManager.php
  lib/MountManager/CircleMountProvider.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, bug
