Repository nextcloud/circles, pull requests merged in 2024-03, with the labels that each got.

#1510 feat: Implement teams dashboard widget
  lib/AppInfo/Application.php
  lib/Dashboard/TeamDashboardWidget.php
Labels: 3. to review, enhancement

#1519 fix: Disable dashboard widget if no frontend is available
  lib/Dashboard/TeamDashboardWidget.php
Labels: 3. to review, bug

#1520 fix(dashboard): Add `icon-teams` CSS class and fix path to app icon
  lib/Dashboard/TeamDashboardWidget.php
Labels: 3. to review, bug

#1521 fix/remove broken scripts
  lib/Listeners/Files/ListenerFilesLoadScripts.php
Labels: 3. to review, bug

#1525 feat: Implement team resource provider for shared files
  composer.lock
  lib/AppInfo/Application.php
  lib/FileSharingTeamResourceProvider.php
Labels: 3. to review, enhancement

#1513 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1365 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
