Repository nextcloud/circles, pull requests merged in 2024-07, with the labels that each got.

#1571 chore(i18n): Established the meaning of the sentence
  lib/Activity/ProviderSubjectCircleMember.php
Labels: 3. to review, feedback-requested

#1583 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1612 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1620 [stable27] fix setIcon using svg
  lib/Activity/Provider.php
Labels: 3. to review, bug

#1623 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1615 ignore empty fileIds
  lib/Service/ShareWrapperService.php
Labels: 3. to review, backport-request, bug, regression

#1641 feat: dismiss notification when accepting an invitation
  lib/AppInfo/Application.php
  lib/Listeners/Notifications/RequestingMember.php
  lib/Service/NotificationService.php
Labels: 3. to review, backport-request, enhancement

#1650 fix(notifications): Don't trigger invite notifications for system groups
  lib/Listeners/Notifications/RequestingMember.php
Labels: 3. to review, bug
