Repository nextcloud/circles, pull requests merged in 2024-10, with the labels that each got.

#1698 fix(CoreQueryBuilder): Use shorter prefixes to stay below 30 characters for Oracle <12.2
  lib/Db/CoreQueryBuilder.php
Labels: 3. to review, backport-request, bug

#1704 fix(notifications): Circles -> Teams references
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug

#1707 fix(notification): Throw new exceptions to stop debug logs
  lib/Activity/Provider.php
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug

#1708 ignore non-circles share while extracting permissions
  lib/ShareByCircleProvider.php
Labels: backport-request

#1684 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1736 fix toArray on null
  lib/Model/ShareWrapper.php
Labels: 3. to review, backport-request, high
