Repository nextcloud/circles, pull requests merged in 2025-02, with the labels that each got.

#1862 fix(occ): handle share wrappers that do not have a circle
  lib/Command/SharesFiles.php
Labels: backport-request

#1877 chore(Application): Remove unused files navigation registration
  lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#1851 lighter link to memberships
  lib/CirclesQueryHelper.php
Labels: backport-request

#1866 fix: Do not send a mail if public share is disabled
  lib/Service/SendMailService.php
Labels: 3. to review, bug

#1829 fix: propagate group name changes
  lib/AppInfo/Application.php
  lib/FederatedItems/CircleEdit.php
  lib/Listeners/GroupChanged.php
  lib/Service/CircleService.php
Labels: 2. developing, bug
