Repository nextcloud/circles, pull requests merged in 2025-07, with the labels that each got.

#2043 build(composer): Stop main composer.json updates propagating to vendor-bin
  composer.json
Labels: 3. to review, bug

#2055 Backport/nc31/2007
  lib/Listeners/Files/ShareCreatedSendMail.php
Labels: 4. to release, bug

#2042 fix(Command): Stop re-rendering tables for each row
  lib/Command/CirclesList.php
  lib/Command/CirclesMemberships.php
  lib/Command/CirclesRemote.php
  lib/Command/CirclesTest.php
  lib/Command/MembersList.php
  lib/Command/MembersSearch.php
  lib/Command/SharesFiles.php
Labels: 3. to review, backport-request, bug

#2063 chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review, backport-request, technical debt

#2064 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#2073 fix: translate name of dashboard widget
  lib/Dashboard/TeamDashboardWidget.php
Labels: 3. to review, backport-request, bug
